yjyd:
  datasource:
    username: root
    password: feng9402
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf8
    driver-class: com.mysql.jdbc.Driver
  url:
    upload:
