yjyd:
  upload:
    username: bsitsqp
    password: bsitsqp
    url: jdbc:oracle:thin:@15.193.248.54:1521:snapall
    driver-class: oracle.jdbc.driver.OracleDriver
    upload-url: http://15.193.242.60:4012/sync/acceptCameras
    upload-username: admin
    upload-password: admin
    upload-opreateuser: 宝山熙菱
    upload-localservername: 宝山熙菱
    # 摄像机类型过滤，编码写在下面的才能上传，用逗号隔开
    filter:
      cameraFuncType: 1
      deviceId: 310113
server:
  port: 9999